// Shared types for the collaboration transport layer.

// The lifecycle of a collab session, surfaced to the UI so it can show
// "waiting for peer", "connected", etc.
export type CollabStatus =
  | 'idle' // not in a session
  | 'connecting' // signaling socket open / WebRTC handshake in flight
  | 'waiting' // joined the room, waiting for the other person to arrive
  | 'connected' // DataChannel open — fully live, peer-to-peer
  | 'peer-left' // the other person disconnected
  | 'room-full' // the room already had 2 people
  | 'disconnected'; // signaling socket/connection dropped

// Messages the SERVER sends us over the signaling WebSocket. The offer/answer/
// ice-candidate ones are relayed verbatim from the other peer; the rest are
// generated by the signaling server itself.
export type SignalInbound =
  | { type: 'joined'; polite: boolean; peerPresent: boolean }
  | { type: 'peer-joined' }
  | { type: 'peer-left' }
  | { type: 'room-full' }
  | { type: 'offer'; sdp: RTCSessionDescriptionInit }
  | { type: 'answer'; sdp: RTCSessionDescriptionInit }
  | { type: 'ice-candidate'; candidate: RTCIceCandidateInit };
